// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp3PaAyF6Wei-LBVUmxWA__J5CU6ADZ_I',
    appId: '1:732110021159:web:920b53161f66ad31f12402',
    messagingSenderId: '732110021159',
    projectId: 'agrilink-se18d03',
    authDomain: 'agrilink-se18d03.firebaseapp.com',
    storageBucket: 'agrilink-se18d03.firebasestorage.app',
    measurementId: 'G-CEK33CQ4L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCPpF_XkouClayCv95cHKWLhOxC2Mrbyg',
    appId: '1:732110021159:android:c0cd95f8255e49c2f12402',
    messagingSenderId: '732110021159',
    projectId: 'agrilink-se18d03',
    storageBucket: 'agrilink-se18d03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-JQpeBsxb3eEV-JnwSo2M9bpcKeE_GCk',
    appId: '1:732110021159:ios:bb449373d4745681f12402',
    messagingSenderId: '732110021159',
    projectId: 'agrilink-se18d03',
    storageBucket: 'agrilink-se18d03.firebasestorage.app',
    iosBundleId: 'com.mai.agrilink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-JQpeBsxb3eEV-JnwSo2M9bpcKeE_GCk',
    appId: '1:732110021159:ios:bb449373d4745681f12402',
    messagingSenderId: '732110021159',
    projectId: 'agrilink-se18d03',
    storageBucket: 'agrilink-se18d03.firebasestorage.app',
    iosBundleId: 'com.mai.agrilink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp3PaAyF6Wei-LBVUmxWA__J5CU6ADZ_I',
    appId: '1:732110021159:web:00bd4e10919eaa5bf12402',
    messagingSenderId: '732110021159',
    projectId: 'agrilink-se18d03',
    authDomain: 'agrilink-se18d03.firebaseapp.com',
    storageBucket: 'agrilink-se18d03.firebasestorage.app',
    measurementId: 'G-VZT6CMH2YW',
  );
}
